pub(crate) mod error;
pub(crate) mod types;


pub use error::Error;
pub use types::{
    category::Category,
    edition::Edition,
    keyword::{
        Keyword,
        kw_abstract::DATA as KW_ABSTRACT_DATA,
        kw_as::DATA as KW_AS_DATA,
        kw_async::DATA as KW_ASYNC_DATA,
        kw_await::DATA as KW_AWAIT_DATA,
        kw_become::DATA as KW_BECOME_DATA,
        kw_box::DATA as KW_BOX_DATA,
        kw_break::DATA as KW_BREAK_DATA,
        kw_const::DATA as KW_CONST_DATA,
        kw_continue::DATA as KW_CONTINUE_DATA,
        kw_crate::DATA as KW_CRATE_DATA,
        kw_do::DATA as KW_DO_DATA,
        kw_dyn::DATA as KW_DYN_DATA,
        kw_else::DATA as KW_ELSE_DATA,
        kw_enum::DATA as KW_ENUM_DATA,
        kw_extern::DATA as KW_EXTERN_DATA,
        kw_false::DATA as KW_FALSE_DATA,
        kw_final::DATA as KW_FINAL_DATA,
        kw_fn::DATA as KW_FN_DATA,
        kw_for::DATA as KW_FOR_DATA,
        kw_gen::DATA as KW_GEN_DATA,
        kw_if::DATA as KW_IF_DATA,
        kw_impl::DATA as KW_IMPL_DATA,
        kw_in::DATA as KW_IN_DATA,
        kw_let::DATA as KW_LET_DATA,
        kw_loop::DATA as KW_LOOP_DATA,
        kw_macro::DATA as KW_MACRO_DATA,
        kw_macro_rules::DATA as KW_MACRO_RULES_DATA,
        kw_match::DATA as KW_MATCH_DATA,
        kw_mod::DATA as KW_MOD_DATA,
        kw_move::DATA as KW_MOVE_DATA,
        kw_mut::DATA as KW_MUT_DATA,
        kw_override::DATA as KW_OVERRIDE_DATA,
        kw_priv::DATA as KW_PRIV_DATA,
        kw_pub::DATA as KW_PUB_DATA,
        kw_raw::DATA as KW_RAW_DATA,
        kw_ref::DATA as KW_REF_DATA,
        kw_return::DATA as KW_RETURN_DATA,
        kw_safe::DATA as KW_SAFE_DATA,
        kw_self_type::DATA as KW_SELF_TYPE_DATA,
        kw_self_value::DATA as KW_SELF_VALUE_DATA,
        kw_static::DATA as KW_STATIC_DATA,
        kw_static_lifetime::DATA as KW_STATIC_LIFETIME_DATA,
        kw_struct::DATA as KW_STRUCT_DATA,
        kw_super::DATA as KW_SUPER_DATA,
        kw_trait::DATA as KW_TRAIT_DATA,
        kw_true::DATA as KW_TRUE_DATA,
        kw_try::DATA as KW_TRY_DATA,
        kw_type::DATA as KW_TYPE_DATA,
        kw_typeof::DATA as KW_TYPEOF_DATA,
        kw_union::DATA as KW_UNION_DATA,
        kw_unsafe::DATA as KW_UNSAFE_DATA,
        kw_unsized::DATA as KW_UNSIZED_DATA,
        kw_use::DATA as KW_USE_DATA,
        kw_virtual::DATA as KW_VIRTUAL_DATA,
        kw_where::DATA as KW_WHERE_DATA,
        kw_while::DATA as KW_WHILE_DATA,
        kw_yield::DATA as KW_YIELD_DATA,
    },
    keyword_data::KeywordData,
};
